### ISSUE TITLE
Creation of Menu Options to Run Scripts

### ISSUE THREAD

**Issue by wgcisotto** [Encode-Club-Solidity-Group-14/project_week_01#2]
### Menu to execute scripts

In order to facilitate the execution of all scripts, I propose the creation of a single script with a menu option that executes all other scripts. 

Example of the menu:
- Deploy 
- Query Proposal by index
- Give Vote rights 
- Delegate Vote 
- Cast Vote 
- Query Results

**Comment by kasmaldev** [comment]
Yes thats good idea.  I agree to your proposal but how do we implement it?

**Comment by wgcisotto** [comment]
We can implement like this example in lesson 11-Lottery:

- https://github.com/Encode-Club-Solidity-Bootcamp-June/11-Lottery/blob/master/Project/scripts/placeABet.ts

Code example: 
![image](https://user-images.githubusercontent.com/39519012/178119338-4cf4216c-446a-4f13-9c2c-3c989968e3b7.png)

each **case** validates the inputs and runs the script.

**Comment by wgcisotto** [comment]
> Yes thats good idea. I agree to your proposal but how do we implement it?

We can implement like this example in lesson 11-Lottery:

- https://github.com/Encode-Club-Solidity-Bootcamp-June/11-Lottery/blob/master/Project/scripts/placeABet.ts

Code example: 
![image](https://user-images.githubusercontent.com/39519012/178119338-4cf4216c-446a-4f13-9c2c-3c989968e3b7.png)

each **case** validates the inputs and runs the script.
